name: "check-branches"
on:
  push:
    branches:
      - "!main"
jobs:
  branch-code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Make environment
        run: make create-environment

      - name: Make requirements
        run: make requirements

      - name: Make security
        run: make security-test

      - name: Make flake
        run: make run-flake

      - name: Make coverage
        run: make check-coverage

      - name: Make testing
        run: make unit-test
