name: "ingestion"
on:
  push:
    branches:
      - main
jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Make environment
        run: make create-environment

      - name: Make requirements
        run: make requirements

      - name: Make security
        run: make security-test

      - name: Make flake
        run: make run-flake

      - name: Make coverage
        run: make check-coverage
